/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import static application.Application.findAll;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Set;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.sql.ResultSetMetaData;
/**
 *
 * @author Dai Phuc
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    
    public SearchPanel STab;
    public AddPanel ATab;
    public RemovePanel RTab;
    public SortPanel SortTab;
    public ExcelPanel ETab;
    public ModifyPanel MTab;
    
    public GUI() {
        initComponents();
        this.setResizable(false);
        this.setSize(new Dimension(1000, 500));
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        MainTab.setLayout(new BorderLayout());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        SearchButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        SortButton = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        ModifyButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        AddButton = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        RemoveButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        ExcelButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        MainTab = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUCTS MANAGEMENT");
        jLabel1.setOpaque(true);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);
        jToolBar1.setEnabled(false);
        jToolBar1.add(jSeparator8);

        SearchButton.setBackground(new java.awt.Color(255, 255, 255));
        SearchButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/Icon/search-icon.png"))); // NOI18N
        SearchButton.setText("Search");
        SearchButton.setFocusable(false);
        SearchButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SearchButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(SearchButton);
        jToolBar1.add(jSeparator1);

        SortButton.setBackground(new java.awt.Color(255, 255, 255));
        SortButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        SortButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/Icon/sort-icon.png"))); // NOI18N
        SortButton.setText("Sort");
        SortButton.setFocusable(false);
        SortButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SortButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(SortButton);
        jToolBar1.add(jSeparator6);

        ModifyButton.setBackground(new java.awt.Color(255, 255, 255));
        ModifyButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ModifyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/Icon/invoice-icon.png"))); // NOI18N
        ModifyButton.setText("Modify");
        ModifyButton.setFocusable(false);
        ModifyButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ModifyButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(ModifyButton);
        jToolBar1.add(jSeparator2);

        AddButton.setBackground(new java.awt.Color(255, 255, 255));
        AddButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/Icon/add-icon.png"))); // NOI18N
        AddButton.setText("Add");
        AddButton.setFocusable(false);
        AddButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(AddButton);
        jToolBar1.add(jSeparator9);

        RemoveButton.setBackground(new java.awt.Color(255, 255, 255));
        RemoveButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        RemoveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/Icon/remove-icon.png"))); // NOI18N
        RemoveButton.setText("Remove");
        RemoveButton.setFocusable(false);
        RemoveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RemoveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(RemoveButton);
        jToolBar1.add(jSeparator3);

        ExcelButton.setBackground(new java.awt.Color(255, 255, 255));
        ExcelButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ExcelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/Icon/excel-icon.png"))); // NOI18N
        ExcelButton.setText("Excel file");
        ExcelButton.setFocusable(false);
        ExcelButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ExcelButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ExcelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcelButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(ExcelButton);

        ExitButton.setBackground(new java.awt.Color(255, 255, 255));
        ExitButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/Icon/exit-icon.png"))); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainTab.setPreferredSize(new java.awt.Dimension(100, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MainTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortButtonActionPerformed
        // TODO add your handling code here:
        if (SortTab == null){
            SortTab=new SortPanel();
            MainTab.addTab("Search", SortTab);
        }
        SortTab.showProduct();
        MainTab.setSelectedComponent(SortTab);
    }//GEN-LAST:event_SortButtonActionPerformed

    private void ExcelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcelButtonActionPerformed
        
        if (ETab == null){
            ETab = new ExcelPanel();
            MainTab.addTab("Excel", ETab);
        }
        ETab.showProduct();
        MainTab.setSelectedComponent(ETab);
        
        ETab.excel();
        
    }//GEN-LAST:event_ExcelButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        // TODO add your handling code here:
        if (RTab == null){
            RTab = new RemovePanel();
            MainTab.addTab("Remove", RTab);
        }
        RTab.showProduct();
        MainTab.setSelectedComponent(RTab);
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        
        this.setVisible(false);
        
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        
        if (STab == null){
            STab = new SearchPanel();
            MainTab.addTab("Search", STab);
        }
        STab.showProduct();
        MainTab.setSelectedComponent(STab);
        
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        
        if (ATab == null){
            ATab = new AddPanel();
            MainTab.addTab("Add", ATab);
        }
        MainTab.setSelectedComponent(ATab);
        ATab.showProduct();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void ModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButtonActionPerformed
        
        if (MTab == null){
            MTab = new ModifyPanel();
            MainTab.addTab("Add", MTab);
        }
        MainTab.setSelectedComponent(MTab);
        MTab.showProduct();
    }//GEN-LAST:event_ModifyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    DefaultTableModel dm = new DefaultTableModel();
    java.util.List <Product> ProductList;
    
    private void getData(){
       
        dm.setRowCount(0);
        ProductList = Application.findAll();
               
        ProductList.forEach(Product -> {
            dm.addRow(new Object[] { Product.getProductID(),
            Product.getProductName(), Product.getOriginPrice(), Product.getPrice(), Product.getAmount()});        
        });
        
        System.out.println(String.valueOf(dm.getColumnCount()) + "\n" + String.valueOf(dm.getRowCount()));
        
    } 
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton ExcelButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTabbedPane MainTab;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton SortButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
