/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Dai Phuc
 */
public class HistoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form HistoryPanel
     */
    
    DefaultTableModel tableModel;
    List <Product> ProductList;
    
    public HistoryPanel() {
        initComponents();
        tableModel = (DefaultTableModel) tbleHistoryChange.getModel();
        showProduct();;
    }
    
    public void tbleHistoryChange() {
        Application pdao = new Application();

        tableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tbleHistoryChange.setModel(tableModel);
        tableModel.addColumn("User");
        tableModel.addColumn("Time");
        tableModel.addColumn("Action");
        tableModel.addColumn("ProductID");
        tableModel.addColumn("Product Name");
        tableModel.addColumn("Origin Price");
        tableModel.addColumn("Price");
        tableModel.addColumn("Number");

//        tbleHistoryChange.getColumnModel().getColumn(0).setMinWidth(80);
//        tbleHistoryChange.getColumnModel().getColumn(0).setMaxWidth(80);
//        tbleHistoryChange.getColumnModel().getColumn(1).setMinWidth(150);
//        tbleHistoryChange.getColumnModel().getColumn(1).setMaxWidth(150);
//        tbleHistoryChange.getColumnModel().getColumn(2).setMinWidth(100);
//        tbleHistoryChange.getColumnModel().getColumn(2).setMaxWidth(100);
//        tbleHistoryChange.getColumnModel().getColumn(3).setMinWidth(100);
//        tbleHistoryChange.getColumnModel().getColumn(3).setMaxWidth(100);
//        tbleHistoryChange.getColumnModel().getColumn(4).setMinWidth(250);
//        tbleHistoryChange.getColumnModel().getColumn(4).setMaxWidth(250);
//        tbleHistoryChange.getColumnModel().getColumn(5).setMinWidth(100);
//        tbleHistoryChange.getColumnModel().getColumn(5).setMaxWidth(100);
//        tbleHistoryChange.getColumnModel().getColumn(6).setMinWidth(100);
//        tbleHistoryChange.getColumnModel().getColumn(6).setMaxWidth(100);
//        tbleHistoryChange.getColumnModel().getColumn(7).setMinWidth(300);
//        tbleHistoryChange.getColumnModel().getColumn(7).setMaxWidth(300);
//        tbleHistoryChange.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);

        
    }
    
    public void showProduct(){
        List <Product> ProductList = Application.findAll2();
        
        tableModel.setRowCount(0);
        
        ProductList.forEach(PD -> { 
            tableModel.addRow(new Object[]{
                PD.getUserName(), PD.getTimeInsert(), PD.getActionType(), PD.getProductIDChange(), PD.getProductNameChange(),
                PD.getOriginPriceChange(), PD.getPriceChange(), PD.getAmountChange()
            });
        });
    }
    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbleHistoryChange = new javax.swing.JTable();
        ClearButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(811, 427));

        tbleHistoryChange.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "User", "Time", "Action", "Product ID", "Product Name", "Origin Price", "Price", "Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbleHistoryChange.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbleHistoryChange);
        if (tbleHistoryChange.getColumnModel().getColumnCount() > 0) {
            tbleHistoryChange.getColumnModel().getColumn(0).setResizable(false);
            tbleHistoryChange.getColumnModel().getColumn(1).setResizable(false);
            tbleHistoryChange.getColumnModel().getColumn(2).setResizable(false);
            tbleHistoryChange.getColumnModel().getColumn(3).setResizable(false);
            tbleHistoryChange.getColumnModel().getColumn(4).setResizable(false);
            tbleHistoryChange.getColumnModel().getColumn(5).setResizable(false);
            tbleHistoryChange.getColumnModel().getColumn(6).setResizable(false);
            tbleHistoryChange.getColumnModel().getColumn(7).setResizable(false);
        }

        ClearButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ClearButton)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ClearButton)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(this, "Do you want to clear history?", "Confirm", JOptionPane.INFORMATION_MESSAGE, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION){
            Application.clear();
        }
        tbleHistoryChange();
    }//GEN-LAST:event_ClearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbleHistoryChange;
    // End of variables declaration//GEN-END:variables
}
